// <auto-generated />
using DataTablePaginationEFCore.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataTablePaginationEFCore.Migrations
{
    [DbContext(typeof(DataTablePaginationEFCoreContext))]
    partial class DataTablePaginationEFCoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataTablePaginationEFCore.Models.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(11,4)");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Pizza 1",
                            Price = 10m
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Blue-Ray",
                            Price = 60m
                        },
                        new
                        {
                            Id = 3L,
                            Description = "DVD",
                            Price = 20m
                        },
                        new
                        {
                            Id = 4L,
                            Description = "T-Shirt",
                            Price = 20.5m
                        },
                        new
                        {
                            Id = 5L,
                            Description = "Computer",
                            Price = 350.99m
                        },
                        new
                        {
                            Id = 6L,
                            Description = "Laptop",
                            Price = 200m
                        },
                        new
                        {
                            Id = 7L,
                            Description = "Car",
                            Price = 5000m
                        },
                        new
                        {
                            Id = 8L,
                            Description = "Mug",
                            Price = 5.5m
                        },
                        new
                        {
                            Id = 9L,
                            Description = "Cup",
                            Price = 2.5m
                        },
                        new
                        {
                            Id = 10L,
                            Description = "Fork",
                            Price = 1.99m
                        },
                        new
                        {
                            Id = 11L,
                            Description = "Knife",
                            Price = 6.5m
                        },
                        new
                        {
                            Id = 12L,
                            Description = "Gift Card",
                            Price = 0.88m
                        },
                        new
                        {
                            Id = 13L,
                            Description = "Chair",
                            Price = 100.87m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
